/**
 *
 * @author Carlos
 */

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.rmi.*;
import javax.swing.DefaultListCellRenderer;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.border.LineBorder;


public class PublicaSuscribeCliente extends javax.swing.JFrame {

    /**
     * Creates new form PublicaSuscribeCliente
     */
    private static PublicaSuscribeCliente interfaz=new PublicaSuscribeCliente();
    private static PublicaSuscribeServidorInterface h;
    private static PublicaSuscribeClienteInterface Objetocliente;
    
    public PublicaSuscribeCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Empresas:");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7", "Item 8", "Item 9", "Item 10" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setToolTipText("");
        jScrollPane1.setViewportView(jList1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tipo de alerta:");

        jRadioButton1.setText("Compra");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Venta");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Valor objetivo:");

        jButton1.setText("Solicitar Alerta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alertas:");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Debes seleccionar el tipo de alerta");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Debes introducir un valor objetivo válido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton1)))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)))
                        .addGap(0, 137, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        interfaz.jRadioButton2.setSelected(false);
    }                                             

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Realizar la solicitud de alerta
        interfaz.jLabel5.setVisible(false);
        interfaz.jLabel6.setVisible(false);
        if(interfaz.jRadioButton1.isSelected()==true || interfaz.jRadioButton2.isSelected()==true){
            try{
                if(Float.parseFloat(interfaz.jTextField1.getText())>0){
                    if(interfaz.jRadioButton1.isSelected()==true){
                        Alerta alerta= new Alerta(Objetocliente,interfaz.jRadioButton1.getText().toLowerCase(), interfaz.jList1.getSelectedValue().toString().toLowerCase(),Float.parseFloat(interfaz.jTextField1.getText()));
                        try{
                            h.RegistroAlerta(alerta);
                            interfaz.jTextArea1.append("Petición de alerta enviada \n");
                            interfaz.jRadioButton1.setSelected(false);
                            interfaz.jTextField1.setText("");
                        }catch(RemoteException kk){
                            interfaz.jTextArea1.append("Error al enviar la alerta: \n");
                            interfaz.jRadioButton1.setSelected(false);
                            interfaz.jTextField1.setText("");
                        }
                        
                    }else{
                        Alerta alerta= new Alerta(Objetocliente, interfaz.jRadioButton2.getText().toLowerCase(),interfaz.jList1.getSelectedValue().toString().toLowerCase(),Float.parseFloat(interfaz.jTextField1.getText()));
                        try{
                            h.RegistroAlerta(alerta);
                            interfaz.jTextArea1.append("Petición de alerta enviada \n");
                            interfaz.jRadioButton2.setSelected(false);
                            interfaz.jTextField1.setText("");
                        }catch(RemoteException kk){
                            interfaz.jTextArea1.append("Error al enviar la alerta: \n");
                            interfaz.jRadioButton2.setSelected(false);
                            interfaz.jTextField1.setText("");
                        }
                    }
                }
                else{
                	interfaz.jLabel6.setVisible(true);
                }
            }catch(NumberFormatException e){
                interfaz.jTextField1.setText("");
                interfaz.jLabel6.setVisible(true);
            }
        }else{
            interfaz.jLabel5.setVisible(true);
            try{
                if(Float.parseFloat(interfaz.jTextField1.getText())>0){
                }
            }catch(NumberFormatException e){
                interfaz.jTextField1.setText("");
                interfaz.jLabel6.setVisible(true);
            }
        }
    }                                        

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        jRadioButton1.setSelected(false);
    }                                             

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Salir
        try{
            h.DesRegistroAlertas(Objetocliente);
        }catch(RemoteException kk){}
        System.exit(0);
    }                          

    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        // Salir
        try{
            h.DesRegistroAlertas(Objetocliente);
        }catch(RemoteException kk){}
        System.exit(0);
    }                 

    public static void main(String args[]) {
        /* Set the System look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("System".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PublicaSuscribeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PublicaSuscribeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PublicaSuscribeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PublicaSuscribeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                interfaz =new PublicaSuscribeCliente();
                Interfaz txtArea = new Interfaz();
                txtArea.cajita= interfaz.jTextArea1;
                interfaz.setTitle("Cliente alertas bolsa Ibex35");
                ImageIcon icono = new ImageIcon("icono.png"); // Definimos el icono de la aplicación
                interfaz.setIconImage(icono.getImage()); // Cambiamos el icono de la aplicación por el previamente definido
                interfaz.getContentPane().setBackground(Color.decode("#7246B2").brighter()); // Cambiamos el color de fondo de la aplicación
                interfaz.jRadioButton1.setBackground(Color.decode("#7246B2").brighter()); // Cambiamos el color de fondo de los radiobutton
                interfaz.jRadioButton1.setForeground(Color.white);
                interfaz.jRadioButton2.setBackground(Color.decode("#7246B2").brighter()); // Cambiamos el color de fondo de los radiobutton
                interfaz.jRadioButton2.setForeground(Color.white);
                interfaz.jButton1.setBackground(Color.decode("#50CC6D")); // Cambiamos el color de fondo de los botones
                interfaz.jButton1.setForeground(Color.white); // Cambiamos el color de la letra de los botones
                interfaz.jButton2.setBackground(Color.decode("#50CC6D")); // Cambiamos el color de fondo de los radiobutton
                interfaz.jButton2.setForeground(Color.white); // Cambiamos el color de la letra de los botones
                interfaz.setVisible(true); // Mostramos la Interfaz
                interfaz.jLabel1.setText("<html><u>"+interfaz.jLabel1.getText()+"</u></html>"); // Subrayamos el texto de las label
                interfaz.jLabel2.setText("<html><u>"+interfaz.jLabel2.getText()+"</u></html>"); // Subrayamos el texto de las label
                interfaz.jLabel3.setText("<html><u>"+interfaz.jLabel3.getText()+"</u></html>"); // Subrayamos el texto de las label
                interfaz.jLabel4.setText("<html><u>"+interfaz.jLabel4.getText()+"</u></html>"); // Subrayamos el texto de las label
                interfaz.jLabel5.setVisible(false); // Ocultamos las label de aviso
                interfaz.jLabel6.setVisible(false); // Ocultamos las label de aviso
                try{
                    int RMIPort=5009;         
                    String hostName ="localhost";
                    String registryURL = "rmi://localhost:" + RMIPort + "/publicasuscribe";  
                    // Casteamos el objeto remoto a una intrerface
                    h = (PublicaSuscribeServidorInterface)Naming.lookup(registryURL);
                    interfaz.jTextArea1.append("Conectado con el servidor\n");
                    Objetocliente = new PublicaSuscribeClienteImpl(txtArea); // Registramos una alerta
                    interfaz.jList1.setModel(h.EnviarEmpresas(Objetocliente));
                    
                } // end try 
                catch (Exception e) {
                    System.out.println("Problema con el cliente: " + e);
                } // end catch
                interfaz.jList1.setSelectedIndex(0); // Por defecto seleccionamos el primer elemento de la lista
                interfaz.jList1.setCellRenderer(new CellRenderer()); // Hacemos que los elementos de la jlist tenga un color de fondo distinto entre elementos contiguos
                interfaz.jList1.setBackground(Color.decode("#7246B2").brighter());
                interfaz.jList1.setBorder(new LineBorder(Color.decode("#50CC6D").brighter(), 0));
                
            }
        });
    }
     
    private static class CellRenderer extends DefaultListCellRenderer { // Clase para renderizar las propiedades los elementos de la lista
        public Component getListCellRendererComponent( JList list, Object value, int index, boolean isSelected, boolean cellHasFocus ) {
            Component c = super.getListCellRendererComponent( list, value, index, isSelected, cellHasFocus );
            if ( index % 2 == 0 ) {
                c.setBackground(Color.decode("#4846B2"));
                c.setForeground(Color.white);
                c.setFont(c.getFont().deriveFont(Font.BOLD));
            }
            else {
                c.setBackground(Color.decode("#807EFF"));
                c.setForeground(Color.white);
                c.setFont(c.getFont().deriveFont(Font.BOLD));
            }
            if(isSelected){
                c.setBackground(Color.decode("#50CC6D"));
                c.setForeground(Color.white);
                c.setFont(c.getFont().deriveFont(Font.BOLD));
            }
            
            return c;
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}